### PR TITLE
Fixed issue with dot separator when decimalScale is set to zero #375

### LINKED ISSUE #375: Incorrect dot handler for input with decimalScale=0
Hi, thank you for your library. It looks cool.

I found the problem when I created the component with the property `decimalScale`.
Steps to reproduce:
1. Create the NumberFormat component with next props:
```
<NumberFormat 
     value={4200} 
     thousandSeparator={true}
     decimalScale={0}
/>
```
2. Try to press or paste the **dot** symbol between zeros
3. Last zero symbol was removed 

You can see my example [here](https://codepen.io/sergei97k/pen/YzPKELM)

P.S. I resolved this issue. I added the property `decimalSeparator={null}`. But I'm not sure, that it's the clear solution (because decimalSeparator should get only "string" type).

### PR DESCRIPTION
**Pull request by sergei97k**
Fixes #375

### CODE REVIEW

File: src/number_format.js [hunk 1]
```diff
@@ -615,7 +615,8 @@ class NumberFormat extends React.Component {
 
     /** Check for any allowed decimal separator is added in the numeric format and replace it with decimal separator */
     if (!format && start === end && allowedDecimalSeparators.indexOf(value[selectionStart]) !== -1  ) {
-      return value.substr(0, selectionStart) + decimalSeparator + value.substr(selectionStart + 1, value.length);
+      const separator = this.props.decimalScale === 0 ? '' : decimalSeparator;
```
Comment (s-yadav) [inline src/number_format.js]: Destruct decimalScale on top of this function.

**Comment by s-yadav** [comment]
Thanks, the changes look good. And sorry for the very late reply. 
There is just a small change. I will merge this and make that change.
