### PR TITLE
Fix linter warnings. Fixes #77

### LINKED ISSUE #77: Fails if value = null
Component fails on null value in props

### PR DESCRIPTION
**Pull request by isnifer**
Hi! Thank you for the component. I want to help with #77

### CODE REVIEW

File: src/number_format.js [hunk 1]
```diff
@@ -128,12 +129,14 @@ class NumberFormat extends React.Component {
   getFloatString(num, props) {
     props = props || this.props;
     const {decimalSeparator, thousandSeparator} = this.getSeparators(props);
-    return num.replace(new RegExp(escapeRegExp(thousandSeparator || ''), 'g'), '').replace(decimalSeparator, '.');
+    const number = num || '';
```
Comment (s-yadav) [inline src/number_format.js]: This can be moved to arguments 
```js
getFloatString(num='', props)
```

File: src/number_format.js [hunk 2]
```diff
@@ -128,12 +129,14 @@ class NumberFormat extends React.Component {
...
+    return number.replace(new RegExp(escapeRegExp(thousandSeparator || ''), 'g'), '').replace(decimalSeparator, '.');
   }
 
   getFloatValue(num, props) {
     props = props || this.props;
-    return parseFloat(this.getFloatString(num, props)) || 0;
+    const number = num || '';
```
Comment (s-yadav) [inline src/number_format.js]: Move to argument

File: src/number_format.js [hunk 3]
```diff
@@ -407,7 +410,8 @@ class NumberFormat extends React.Component {
     const {state, props} = this;
     const {isAllowed} = props;
     const lastValue = state.value;
-    let {formattedValue, value} = this.formatInput(inputValue);
+    const {value} = this.formatInput(inputValue);
```
Comment (s-yadav) [inline src/number_format.js]: Calling formatInput twice is not a good idea just to maintain const and let.
You can probably store it in some different variable. 
```js
const values = this.formatInput(inputValue);
const {value} = values;
let {formattedValue} = values;
```
Or I will prefer just to disable eslint for this line
  ```js 
 let {formattedValue, value} = this.formatInput(inputValue); // eslint-disable-line prefer-const
```

File: src/number_format.js (hunk 1 above)
Comment (isnifer) [inline src/number_format.js]: No no, it will not override `null`. Only if you pass `undefined` as the first argument, num will be `''`

File: src/number_format.js (hunk 2 above)
Comment (isnifer) [inline src/number_format.js]: the same

**Comment by isnifer** [comment]
@s-yadav hey

File: src/number_format.js (hunk 1 above)
Comment (s-yadav) [reply src/number_format.js]: Ohh yes, 
Instead of creating new const just change it to
```js
num = num || '';
```
or
```js
return (num || '').replace(new RegExp(escapeRegExp(thousandSeparator || ''), 'g'), '').replace(decimalSeparator, '.');
```

File: src/number_format.js (hunk 2 above)
Comment (s-yadav) [reply src/number_format.js]: same

**Comment by s-yadav** [comment]
Also can you make a check for null here as well
https://github.com/isnifer/react-number-format/blob/028d767201f2d227e53719ed0af8ffe5d9dc7e5d/src/number_format.js#L148

**Comment by isnifer** [comment]
@s-yadav got it https://github.com/s-yadav/react-number-format/pull/80/files#diff-520385b0e4cf9fbd5592b5e80fb833f0R146

File: src/number_format.js [hunk 4]
```diff
@@ -128,12 +129,12 @@ class NumberFormat extends React.Component {
...
     props = props || this.props;
     const {decimalSeparator, thousandSeparator} = this.getSeparators(props);
-    return num.replace(new RegExp(escapeRegExp(thousandSeparator || ''), 'g'), '').replace(decimalSeparator, '.');
+    return (num || '').replace(new RegExp(escapeRegExp(thousandSeparator || ''), 'g'), '').replace(decimalSeparator, '.');
   }
 
   getFloatValue(num, props) {
     props = props || this.props;
-    return parseFloat(this.getFloatString(num, props)) || 0;
+    return parseFloat(this.getFloatString(num || '', props)) || 0;
```
Comment (s-yadav) [inline src/number_format.js]: Here or operation is not required as it's already been done on getFloatString

File: src/number_format.js [hunk 5]
```diff
@@ -142,7 +143,7 @@ class NumberFormat extends React.Component {
 
     let {value} = props;
 
-    if (format || value === undefined || value === '') return value;
+    if (format || !value) return value;
```
Comment (s-yadav) [inline src/number_format.js]: This will return in case value is 0 as well. It shouldn't

Comment (s-yadav) [reply src/number_format.js]:
```js
if (format || !(value || value === 0)) return value;
```

**Comment by isnifer** [comment]
@s-yadav hope, that's all

File: src/number_format.js [hunk 6]
```diff
@@ -84,6 +84,7 @@ const defaultProps = {
   suffix: '',
   allowNegative: true,
   type: 'text',
+  value: '',
```
Comment (s-yadav) [inline src/number_format.js]: Test failing because of this as if value is not provided we treat it as an uncontrolled component.
